name: densehybrid
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - pillow
  - tqdm
  - requests
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly  # remove this if you have a GPU with CUDA
  - pip:
      - blosc2==2.0.0
      - click==8.1.7
      - cmake==3.27.2
      - contourpy==1.1.0
      - cox==0.1.post3
      - cycler==0.11.0
      - cython==3.0.0
      - dill==0.3.7
      - easydict==1.10
      - einops==0.6.1
      - filelock==3.12.2
      - fonttools==4.42.1
      - fsspec==2023.9.2
      - gensim==4.3.2
      - gitdb==4.0.10
      - gitpython==3.1.32
      - gputil==1.4.0
      - grpcio==1.57.0
      - huggingface-hub==0.17.3
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.4
      - lit==16.0.6
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - msgpack==1.0.5
      - networkx==3.1
      - nltk==3.8.1
      - numexpr==2.8.5
      - opencv-python==4.8.1.78
      - packaging==23.1
      - protobuf==4.24.1
      - psutil==5.9.5
      - py-cpuinfo==9.0.0
      - py3nvml==0.2.7
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - regex==2023.8.8
      - safetensors==0.4.0
      - seaborn==0.12.2
      - six==1.16.0
      - smart-open==6.3.0
      - smmap==5.0.0
      - sympy==1.12
      - tables==3.8.0
      - tensorboardx==2.6.2.2
      - termcolor==2.3.0
      - texttable==1.6.7
      - threadpoolctl==3.2.0
      - timm==0.9.0
      - tokenizers==0.14.1
      - transformers==4.34.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==2.0.4
      - xmltodict==0.13.0
